server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**
        - id: attendance-service
          uri: lb://attendance-service
          predicates:
            - Path=/api/attendance/**
        - id: leave-service
          uri: lb://leave-service
          predicates:
            - Path=/api/leaves/**
        - id: payroll-service
          uri: lb://payroll-service
          predicates:
            - Path=/api/payroll/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
